'use client';

export function AcademicProjects() {
  const projects = [
    {
      title: "RF Low Noise Amplifier Design (Cadence)",
      description: "Designed a Low Noise Amplifier for a given frequency band. Simulated S-parameters and noise performance. Performed Monte Carlo analysis to study circuit behavior under PVT variations.",
      tags: ["RF", "Cadence", "LNA", "Analog"],
    },
    {
      title: "Acoustic Source Localization using Neural Networks (Jul 2020 – Dec 2020)",
      description: "Developed a non-invasive intelligent fault detection system for steel industrial machinery using source localization and CNNs. Custom dataset generated by convolving machine sounds with room impulse responses. Entirely built using PyTorch.",
      tags: ["Signal Processing", "CNN", "PyTorch", "Acoustics"],
    },
    {
      title: "2-DoF Accelerometer Simulation (CoventorMP)",
      description: "Designed and simulated a 2 degrees-of-freedom MEMS accelerometer based on interdigitated capacitor structures using CoventorMP.",
      tags: ["MEMS", "CoventorMP", "Simulation"],
    },
    {
      title: "TMR Angle Sensor Signal Conditioner (Dec 2022)",
      description: "Simulated and designed a PCB for a linearizing signal conditioning circuit for a half-bridge based TMR angle sensor.",
      tags: ["TMR", "Sensor Interface", "PCB", "Analog"],
    },
  ];

  return (
    <ul className="space-y-6">
      {projects.map((proj, i) => (
        <li key={i} className="border-l-4 border-yellow-600 pl-4">
          <h3 className="text-xl font-semibold">{proj.title}</h3>
          <p className="text-sm text-gray-700 mt-1">{proj.description}</p>
          <div className="text-xs text-yellow-800 mt-2 space-x-2">
            {proj.tags.map((tag, j) => (
              <span key={j} className="bg-yellow-200 px-2 py-0.5 rounded">{tag}</span>
            ))}
          </div>
        </li>
      ))}
    </ul>
  );
}
